#!/usr/bin/env bash
#!bash script that displays Best School 10 times and hi on 9th
x=1
while [ $x -le 10 ]
do
	echo Best School
	((x++))
	if [ $x == 9 ]
	then
		echo Best School
		echo Hi
		((x++))
	fi
done
